<?php

/**
 * @file
 * Contains pusher.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * page_attachments hook
 */

function pusher_integration_page_attachments(&$page) {
	// Include Pusher
	$appKey = \Drupal::config('pusher_integration.settings')->get('pusherAppKey');
	$clusterName = \Drupal::config('pusher_integration.settings')->get('clusterName');

	$page['#attached']['library'][] = 'pusher_integration/pusherIntegration';
	$page['#attached']['drupalSettings']['pusher']['pusherAppKey'] = $appKey;
	$page['#attached']['drupalSettings']['pusher']['clusterName'] = $clusterName;
	$page['#attached']['drupalSettings']['pusher']['userHash'] = $userHash;
}

function pusher_integration_page_attachments_alter(&$page)
{
	// Disable caching of this stuff, otherwise, all sorts of issues occur
	$page['#cache'] = ['max-age' => 0];

	$isUserAnonymous = \Drupal::currentUser()->isAnonymous();
	$defaultChannels = \Drupal::config('pusher_integration.settings')->get('defaultChannels');
	$channelPaths = \Drupal::config('pusher_integration.settings')->get('channelPaths');

	$page['#attached']['drupalSettings']['pusher']['isUserAnonymous'] = $isUserAnonymous;

	// Default Channels (everyone gets these if set)
	$tmp = preg_split('/\n/', $defaultChannels);
	$defaultChannels = array_filter($tmp);
	$page['#attached']['drupalSettings']['pusher']['defaultChannels'] = $defaultChannels;

	// Channel routes (specific channels mapped to specific path patterns)
	//$currentRoute = \Drupal::request()->get(Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_NAME);
	$currentPath = \Drupal::request()->getRequestUri();
	$pathHash = md5( $currentPath );
	$page['#attached']['drupalSettings']['pusher']['pathHash'] = $pathHash;
	$page['#attached']['drupalSettings']['pusher']['privateChannelName'] = 'private-' . $pathHash;


	$tmp = preg_split('/\n/', $channelPaths);
	$channelPaths = array_filter($tmp);


	$matchedChannels = array();

	// See if any configure channel paths match the current route, if so, add the channel to the list we need to connect to
	foreach ($channelPaths as $line) {

		list($channelName, $pattern) = preg_split('/\|/', $line);

		$pattern = trim($pattern);
		$channelName = trim($channelName);

		$pattern = str_replace('/', '\/', $pattern);

		if (preg_match('/' . $pattern . '/', $currentPath)) {
			$matchedChannels[] = $channelName;
		}
	}
	$page['#attached']['drupalSettings']['pusher']['matchedChannels'] = $matchedChannels;

}

