<?php

/**
 * @file
 * Contains pusher.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * page_attachments hook
 */

function pusher_integration_page_attachments(&$page) {
	// Include Pusher
	$appKey = \Drupal::config('pusher_integration.settings')->get('pusherAppKey');
	$clusterName = \Drupal::config('pusher_integration.settings')->get('clusterName');
	$createPrivateChannel = \Drupal::config('pusher_integration.settings')->get('createPrivateChannel');
	$createPresenceChannel = \Drupal::config('pusher_integration.settings')->get('createPresenceChannel');
	$presenceChannelName = \Drupal::config('pusher_integration.settings')->get('presenceChannelName');

	// Create a name for the private channel for the current user, if it has been enabled
	if ($createPrivateChannel) {
		$account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
		$userName = $account->get('name')->value;
		$userHash = md5( $account->get('created')->login );
		$privateChannelName = 'private-' . $username . '-' . $userHash;
	}
	else
		$privateChannelName = 'private-disabled';

	$page['#attached']['library'][] = 'pusher_integration/pusherIntegration';
	$page['#attached']['drupalSettings']['pusher']['pusherAppKey'] = $appKey;
	$page['#attached']['drupalSettings']['pusher']['clusterName'] = $clusterName;
	$page['#attached']['drupalSettings']['pusher']['createPrivateChannel'] = $createPrivateChannel;
	$page['#attached']['drupalSettings']['pusher']['privateChannelName'] = $privateChannelName;
	$page['#attached']['drupalSettings']['pusher']['createPresenceChannel'] = $createPresenceChannel;
	$page['#attached']['drupalSettings']['pusher']['presenceChannelName'] = $presenceChannelName;
}

function pusher_integration_page_attachments_alter(&$page)
{
	// Disable caching of this stuff, otherwise, all sorts of issues occur
	$page['#cache'] = ['max-age' => 0];

	$isUserAnonymous = \Drupal::currentUser()->isAnonymous();
	$defaultChannels = \Drupal::config('pusher_integration.settings')->get('defaultChannels');
	$channelPaths = \Drupal::config('pusher_integration.settings')->get('channelPaths');

	$page['#attached']['drupalSettings']['pusher']['isUserAnonymous'] = $isUserAnonymous;

	// Default Channels (everyone gets these if set)
	$tmp = preg_split('/\n/', $defaultChannels);
	$defaultChannels = array_filter($tmp);
	$page['#attached']['drupalSettings']['pusher']['defaultChannels'] = $defaultChannels;

	// Channel routes (specific channels mapped to specific path patterns)
	//$currentRoute = \Drupal::request()->get(Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_NAME);
	$currentPath = \Drupal::request()->getRequestUri();

	$tmp = preg_split('/\n/', $channelPaths);
	$channelPaths = array_filter($tmp);

	$matchedChannels = array();

	// See if any configure channel paths match the current route, if so, add the channel to the list we need to connect to
	foreach ($channelPaths as $line) {

		list($channelName, $pattern) = preg_split('/\|/', $line);

		$pattern = trim($pattern);
		$pattern = str_replace('/', '\/', $pattern);

		if (preg_match('/' . $pattern . '/', $currentPath)) {
			$matchedChannels[] = $channelName;
		}
	}
	$page['#attached']['drupalSettings']['pusher']['matchedChannels'] = $matchedChannels;

}

