pusher_integration.channel_path_map.*:
  type: config_entity
  label: 'Channel-Path-Map Entry'
  mapping:
    mapId:
      type: string
      label: 'Map ID'
    channelName:
      type: string
      label: 'Pusher Channel Name'
    pathPattern:
      type: string
      label: 'Path Pattern'
